version: '3.1'

services:
  mysql_db:
    image: mysql:latest
    container_name: mysql_db
    ports:
      - "3306:3306"
    environment:
      MYSQL_DATABASE: central
      MYSQL_USER: appuser
      MYSQL_PASSWORD: root
      MYSQL_ROOT_PASSWORD: root
    volumes:
      - mysql_data:/var/lib/mysql
    restart: unless-stopped
    healthcheck:
      test: [ "CMD", "mysqladmin", "ping", "-h", "localhost" ]
      interval: 10s
      timeout: 5s
      retries: 5

  postgres_db-ns:
    image: postgres:latest
    container_name: postgres_db-ns
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: root
      POSTGRES_DB: city_db
    ports:
      - "5432:5432"
    volumes:
      - postgres_data-ns:/var/lib/postgresql/data
    healthcheck:
      test:
        [
          "CMD-SHELL",
          "pg_isready -U user -d city_db -h localhost"
        ]
      interval: 10s
      timeout: 5s
      retries: 5

  postgres_db-bg:
    image: postgres:latest
    container_name: postgres_db-bg
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: root
      POSTGRES_DB: city_db
    ports:
      - "5433:5432"
    volumes:
      - postgres_data-bg:/var/lib/postgresql/data
    healthcheck:
      test:
        [
          "CMD-SHELL",
          "pg_isready -U user -d city_db -h localhost"
        ]
      interval: 10s
      timeout: 5s
      retries: 5

  postgres_db-ni:
    image: postgres:latest
    container_name: postgres_db-ni
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: root
      POSTGRES_DB: city_db
    ports:
      - "5434:5432"
    volumes:
      - postgres_data-ni:/var/lib/postgresql/data
    healthcheck:
      test:
        [
          "CMD-SHELL",
          "pg_isready -U user -d city_db -h localhost"
        ]
      interval: 10s
      timeout: 5s
      retries: 5

  central:
    build: mgravara/centrallibrary:0.0.1
    container_name: central_app
    environment:
      - ConnectionStrings__LibraryDbContext=server=mysql_db;database=central;user=appuser;password=root
    restart: always
    ports:
      - 5292:5292
      - 8083:8080
    depends_on:
      mysql_db:
        condition: service_healthy

  city-ns:
    image: mgravara/citylibrary:0.0.1
    container_name: city-ns
    environment:
      - CENTRAL_APP_BASE_URL=http://central_app:8080
      - SPRING_DATASOURCE_URL=jdbc:postgresql://postgres_db-ns/city_db
      - SPRING_DATASOURCE_USERNAME=user
      - SPRING_DATASOURCE_PASSWORD=root
    restart: always
    ports:
      - 8081:8081
    depends_on:
      postgres_db-ns:
        condition: service_healthy

  city-bg:
    image: mgravara/citylibrary:0.0.1
    container_name: city-bg
    environment:
      - CENTRAL_APP_BASE_URL=http://central_app:8080
      - SPRING_DATASOURCE_URL=jdbc:postgresql://postgres_db-bg/city_db
      - SPRING_DATASOURCE_USERNAME=user
      - SPRING_DATASOURCE_PASSWORD=root
    restart: always
    ports:
      - 8082:8081
    depends_on:
      postgres_db-bg:
        condition: service_healthy

  city-ni:
    image: mgravara/citylibrary:0.0.1
    container_name: city-ni
    environment:
      - CENTRAL_APP_BASE_URL=http://central_app:8080
      - SPRING_DATASOURCE_URL=jdbc:postgresql://postgres_db-ni/city_db
      - SPRING_DATASOURCE_USERNAME=user
      - SPRING_DATASOURCE_PASSWORD=root
    restart: always
    ports:
      - 8084:8081
    depends_on:
      postgres_db-ni:
        condition: service_healthy

volumes:
  mysql_data:
  postgres_data-ns:
  postgres_data-bg:
  postgres_data-ni:
