apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: library-ingress
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /$2
spec:
  ingressClassName: nginx
  rules:
  - host: gravara.com
    http:
      paths:
      - pathType: ImplementationSpecific
        path: "/central(/|$)(.*)"
        backend:
          service:
            name: central-library-service
            port: 
              number: 8080
      - pathType: ImplementationSpecific
        path: "/city-ns(/|$)(.*)"
        backend:
          service:
            name: city-library-ns-service
            port: 
              number: 8081
      - pathType: ImplementationSpecific
        path: "/city-bg(/|$)(.*)"
        backend:
          service:
            name: city-library-bg-service
            port: 
              number: 8081
      - pathType: ImplementationSpecific
        path: "/city-ni(/|$)(.*)"
        backend:
          service:
            name: city-library-ni-service
            port: 
              number: 8081
