name: Publish Docker Images

on:
  push:
    branches: [ master ]

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    steps:
    - name: Check Out Repo
      uses: actions/checkout@v2

    - name: Log in to Docker Hub
      uses: docker/login-action@v1
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}

    - name: Build and Push CentralLibrary Image
      uses: docker/build-push-action@v2
      with:
        context: ./CentralLibrary
        file: ./CentralLibrary/Dockerfile
        push: true
        tags: gravara/centrallibrary:latest

    - name: Build and Push CityLibrary Image
      uses: docker/build-push-action@v2
      with:
        context: ./CityLibrary
        file: ./CityLibrary/Dockerfile
        push: true
        tags: gravara/citylibrary:latest
